global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: otel-collector  
    scrape_interval: 10s  
    static_configs:
    - targets: ['otel:8889', 'otel:8888']

  # - job_name: 'cadvisor'
  #   static_configs:
  #   - targets: ['cadvisor:8080']

  - job_name: weatherforecast-api
    scrape_interval: 10s
    static_configs:
    - targets: ['host.docker.internal:7000', '0.0.0.0:5150']      

